import { Download } from 'lucide-react';
import type { CheckResult } from '../types';
interface Props{result:CheckResult}
const labels={REAL:'Признаки генерации не выражены',FAKE:'Найдены признаки AI-генерации',UNCERTAIN:'Требуется дополнительная проверка'};
const status={REAL:'text-mv-real',FAKE:'text-mv-fake',UNCERTAIN:'text-mv-uncertain'};
export function CheckResultCard({result}:Props){const rows=[['01 · Вывод модели',labels[result.verdict],status[result.verdict]],['02 · Метод анализа',result.model_used,'text-mv-text'],['03 · Время обработки',`${result.processing_ms} мс`,'text-mv-text']];return <article className="bg-white border border-black/[.09] rounded-[20px] shadow-[0_1px_2px_rgba(0,0,0,.04),0_24px_60px_rgba(0,0,0,.07)] overflow-hidden">
  <header className="p-6 sm:p-9 flex flex-col sm:flex-row sm:items-start justify-between gap-6"><div><p className="eyebrow mb-3">Отчёт о проверке · {new Date().toLocaleDateString('ru-RU')}</p><h2 className="text-2xl font-semibold tracking-[-.035em]">Результат анализа</h2><p className="text-xs text-mv-text-muted mt-2">ID · {result.model_used}</p></div><div className="sm:text-right"><p className={`text-sm ${status[result.verdict]}`}>{labels[result.verdict]}</p><p className="text-5xl font-semibold tracking-[-.06em] mt-2">{result.confidence}<span className="text-xl text-mv-text-muted">%</span></p><p className="text-xs text-mv-text-muted mt-1">индекс подлинности</p></div></header>
  <div className="border-t border-black/[.07] p-6 sm:p-9 grid lg:grid-cols-[1fr_300px] gap-10"><div><p className="eyebrow mb-5">Общий вывод</p><h3 className="text-2xl sm:text-3xl font-semibold tracking-[-.04em] leading-tight">{labels[result.verdict]}</h3><p className="text-mv-text-secondary leading-7 mt-4 max-w-xl">{result.explanation}</p></div><aside className="bg-[#f4f4f2] border border-black/[.06] rounded-[14px] p-5"><p className="text-xs font-semibold mb-3">Рекомендация</p><p className="text-sm text-mv-text-secondary leading-6">Используйте результат вместе с контекстом материала. Для значимых решений проведите ручную проверку источника.</p></aside></div>
  {result.short_report && <section className="px-6 sm:px-9 pb-8"><p className="eyebrow mb-3">Краткий отчёт</p><p className="max-w-3xl text-sm sm:text-base text-mv-text-secondary leading-7">{result.short_report}</p></section>}
  <section className="px-6 sm:px-9 pb-8"><p className="eyebrow mb-3">Основные признаки</p>{rows.map(r=><div key={r[0]} className="grid sm:grid-cols-2 gap-2 py-4 border-t border-black/[.07] text-sm"><span className="text-mv-text-secondary">{r[0]}</span><span className={`${r[2]} sm:text-right`}>{r[1]}</span></div>)}</section>
	  <footer className="px-6 sm:px-9 py-5 bg-[#fafaf9] border-t border-black/[.07] flex justify-end"><button className="btn-black !min-h-[40px]" onClick={()=>window.print()}><Download size={15}/>Экспортировать PDF</button></footer>
  </article>}
