import { Download } from 'lucide-react';
import type { CheckResult } from '../types';
import { displayAuthenticityIndex, displayModelName } from '../lib/resultPresentation';
interface Props{result:CheckResult}
const labels={REAL:'Признаки генерации не выражены',FAKE:'Найдены признаки AI-генерации',UNCERTAIN:'Требуется дополнительная проверка'};
const status={REAL:'text-mv-real',FAKE:'text-mv-fake',UNCERTAIN:'text-mv-uncertain'};
const credibilityLabels={VERY_LOW_CREDIBILITY:'Крайне низкая достоверность',LOW_CREDIBILITY:'Низкая достоверность',MIXED_CREDIBILITY:'Спорная достоверность',MOSTLY_CREDIBLE:'Преимущественно достоверный материал',HIGH_CREDIBILITY:'Высокая достоверность'};
const safeUrl=(value:string)=>{try{const url=new URL(value);const host=url.hostname.toLowerCase().replace(/\.$/,'');const privateV4=/^(127|10)\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(host);return (url.protocol==='https:'||url.protocol==='http:')&&host!=='localhost'&&!host.endsWith('.localhost')&&!privateV4?url.href:null}catch{return null}};
export function CheckResultCard({result}:Props){const aiUnavailable=result.ai_status==='unavailable';const authenticityIndex=aiUnavailable?null:displayAuthenticityIndex(result.authenticity_index,result.confidence,result.verdict);const modelName=displayModelName(result.model_used);const credibility=result.credibility;const credibilityIndex=credibility?.status==='completed'&&typeof credibility.credibility_index==='number'?credibility.credibility_index:null;const aiLabel=aiUnavailable?'Проверка AI-происхождения временно недоступна':labels[result.verdict];const rows=[['01 · Вывод модели',aiLabel,aiUnavailable?'text-mv-text-secondary':status[result.verdict]],['02 · Метод анализа',modelName,'text-mv-text'],['03 · Время обработки',`${result.processing_ms} мс`,'text-mv-text']];return <article className="bg-white border border-black/[.09] rounded-[20px] shadow-[0_1px_2px_rgba(0,0,0,.04),0_24px_60px_rgba(0,0,0,.07)] overflow-hidden">
  <header className="p-6 sm:p-9 flex flex-col sm:flex-row sm:items-start justify-between gap-6"><div><p className="eyebrow mb-3">Отчёт о проверке · {new Date().toLocaleDateString('ru-RU')}</p><h2 className="text-2xl font-semibold tracking-[-.035em]">Результат анализа</h2><p className="text-xs text-mv-text-muted mt-2">Метод · {modelName}</p></div><div className="sm:text-right"><p className={`text-sm ${aiUnavailable?'text-mv-text-secondary':status[result.verdict]}`}>{aiLabel}</p>{authenticityIndex!==null&&<><p className="text-5xl font-semibold tracking-[-.06em] mt-2">{authenticityIndex}<span className="text-xl text-mv-text-muted">%</span></p><p className="text-xs text-mv-text-muted mt-1">индекс подлинности</p></>}</div></header>
  <div className="border-t border-black/[.07] p-6 sm:p-9 grid lg:grid-cols-[1fr_300px] gap-10"><div><p className="eyebrow mb-5">Общий вывод</p><h3 className="text-2xl sm:text-3xl font-semibold tracking-[-.04em] leading-tight">{aiLabel}</h3><p className="text-mv-text-secondary leading-7 mt-4 max-w-xl">{result.explanation}</p></div><aside className="bg-[#f4f4f2] border border-black/[.06] rounded-[14px] p-5"><p className="text-xs font-semibold mb-3">Рекомендация</p><p className="text-sm text-mv-text-secondary leading-6">Используйте результат вместе с контекстом материала. Для значимых решений проведите ручную проверку источника.</p></aside></div>
  {result.short_report && <section className="px-6 sm:px-9 pb-8"><p className="eyebrow mb-3">Краткий отчёт</p><p className="max-w-3xl text-sm sm:text-base text-mv-text-secondary leading-7">{result.short_report}</p></section>}
  {credibility && <section className="px-6 sm:px-9 pb-8"><div className="border-t border-black/[.07] pt-7"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow mb-2">Достоверность</p><h3 className="text-xl font-semibold tracking-[-.03em]">{credibilityIndex===null?'Проверка временно недоступна':credibilityLabels[credibility.verdict || 'MIXED_CREDIBILITY']}</h3></div>{credibilityIndex!==null&&<p className="text-3xl font-semibold tracking-[-.05em]">{credibilityIndex}<span className="text-base text-mv-text-muted">%</span></p>}</div>{credibilityIndex!==null&&<div className="h-2 rounded-full bg-[#ecece9] mt-5 overflow-hidden"><div className="h-full bg-mv-text rounded-full" style={{width:`${credibilityIndex}%`}}/></div>}<p className="text-mv-text-secondary leading-7 mt-4 max-w-3xl">{credibility.summary}</p>{credibility.issues.length>0&&<div className="mt-6"><p className="eyebrow mb-3">Ключевые несоответствия</p><ol className="space-y-3 text-sm text-mv-text-secondary leading-6">{credibility.issues.map((issue,index)=><li key={`${issue.type}-${index}`}><span className="font-semibold text-mv-text">{index+1}. {issue.claim}</span><br/>{issue.explanation}</li>)}</ol></div>}{credibility.sources.length>0&&<div className="mt-6"><p className="eyebrow mb-3">Источники</p><ol className="space-y-2 text-sm">{credibility.sources.map((source,index)=>{const url=safeUrl(source.url);return <li key={`${source.url}-${index}`}>{url?<a className="text-mv-text underline underline-offset-4" href={url} target="_blank" rel="noreferrer">[{index+1}] {source.title}</a>:<span className="text-mv-text-secondary">[{index+1}] {source.title}</span>}</li>})}</ol></div>}</div></section>}
  <section className="px-6 sm:px-9 pb-8"><p className="eyebrow mb-3">Основные признаки</p>{rows.map(r=><div key={r[0]} className="grid sm:grid-cols-2 gap-2 py-4 border-t border-black/[.07] text-sm"><span className="text-mv-text-secondary">{r[0]}</span><span className={`${r[2]} sm:text-right`}>{r[1]}</span></div>)}</section>
	  <footer className="px-6 sm:px-9 py-5 bg-[#fafaf9] border-t border-black/[.07] flex justify-end"><button className="btn-black !min-h-[40px]" onClick={()=>window.print()}><Download size={15}/>Экспортировать PDF</button></footer>
  </article>}
